### ISSUE TITLE
SNAP install sous Linux : Ringover ne se lance pas

### ISSUE THREAD

**Issue by adelcasse** [ringover/ringover-desktop-v2#4]
J'ai essayé d'installer Ringover avec le package snap sous Ubuntu. En mode "classic" comment en mode "normal". L'interface ne se lance pas. 

Depuis la console, j'ai ceci: 

$ ringover 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /snap/ringover/x1/resources/app.asar.unpacked/node_modules/@gnaudio/jabra-node-sdk/build/Release/sdkintegration.node)
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2073)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at bindings (/snap/ringover/x1/resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/snap/ringover/x1/resources/app.asar/node_modules/@gnaudio/jabra-node-sdk/dist/main/logger.js:10:22)

(ringover:951499): Gtk-WARNING **: 14:46:19.838: Theme parsing error: gtk.css:1566:23: 'font-feature-settings' is not a valid property name

(ringover:951499): Gtk-WARNING **: 14:46:19.857: Theme parsing error: gtk.css:3618:25: 'font-feature-settings' is not a valid property name

(ringover:951499): Gtk-WARNING **: 14:46:19.858: Theme parsing error: gtk.css:4080:23: 'font-feature-settings' is not a valid property name

**Comment by koussaimb** [comment]
Bonjour, 

le probleme est fixé, vous pouvez installer ringover depuis le snpa store via cette page 

https://snapcraft.io/ringover

merci de installer cette module avant sudo snap connect ringover:pulseaudio
